### ISSUE TITLE
22.06.01 crashes after some time on Synology 

### ISSUE THREAD

**Issue by yieldhog** [bachya/ecowitt2mqtt#166] opened 2022-06-10 03:52 UTC
**Describe the bug**
Unexpected crash, hasn't occurred under any prior versions, log below

`

date | stream | content
-- | -- | --
2022-06-09T21:54:51.662711400Z | stdout | Aborted (core dumped)
2022-06-09T21:54:50.632490521Z | stdout | Extension modules: uvloop.loop, _ruamel_yaml, Levenshtein._levenshtein, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.config, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic (total: 26)
2022-06-09T21:54:50.632449005Z | stdout |  
2022-06-09T21:54:50.632377603Z | stdout | File "/venv/bin/ecowitt2mqtt", line 8 in <module>
2022-06-09T21:54:50.632324854Z | stdout | File "/venv/lib/python3.10/site-packages/typer/main.py", line 214 in __call__
2022-06-09T21:54:50.632274566Z | stdout | File "/venv/lib/python3.10/site-packages/click/core.py", line 1130 in __call__
2022-06-09T21:54:50.632227181Z | stdout | File "/venv/lib/python3.10/site-packages/click/core.py", line 1055 in main
2022-06-09T21:54:50.632178998Z | stdout | File "/venv/lib/python3.10/site-packages/click/core.py", line 1635 in invoke
2022-06-09T21:54:50.632130675Z | stdout | File "/venv/lib/python3.10/site-packages/click/core.py", line 1404 in invoke
2022-06-09T21:54:50.632081092Z | stdout | File "/venv/lib/python3.10/site-packages/click/core.py", line 760 in invoke
2022-06-09T21:54:50.632028514Z | stdout | File "/venv/lib/python3.10/site-packages/typer/main.py", line 500 in wrapper
2022-06-09T21:54:50.631970473Z | stdout | File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/logging.py", line 47 in wrapper
2022-06-09T21:54:50.631917737Z | stdout | File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/cli.py", line 187 in main
2022-06-09T21:54:50.631866742Z | stdout | File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/core.py", line 45 in start
2022-06-09T21:54:50.631813238Z | stdout | File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/server.py", line 76 in start
2022-06-09T21:54:50.631765879Z | stdout | Current thread 0x00007fba82916b48 (most recent call first):
2022-06-09T21:54:50.631726075Z | stdout |  
2022-06-09T21:54:50.631676199Z | stdout | File "/usr/local/lib/python3.10/threading.py", line 973 in _bootstrap
2022-06-09T21:54:50.631615112Z | stdout | File "/usr/local/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
2022-06-09T21:54:50.631457273Z | stdout | File "/usr/local/lib/python3.10/threading.py", line 953 in run
2022-06-09T21:54:50.631328720Z | stdout | File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 81 in _worker
2022-06-09T21:54:50.631230879Z | stdout | Thread 0x00007fba7df65b38 (most recent call first):
2022-06-09T21:54:50.631189226Z | stdout |  
2022-06-09T21:54:50.631016869Z | stdout | Fatal Python error: Aborted
2022-06-09T21:54:50.630410436Z | stdout | [94m2022-06-09 21:54:50,629 \| ecowitt2mqtt \| DEBUG \| Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b''[0m
2022-06-09T21:54:50.629751345Z | stdout | [94m2022-06-09 21:54:50,627 \| ecowitt2mqtt \| DEBUG \| Calculator found for soilbatt1: calculate_battery (key: soilbatt1, value: 1.5)[0m
2022-06-09T21:54:50.629190237Z | stdout | [94m2022-06-09 21:54:50,627 \| ecowitt2mqtt \| DEBUG \| Calculator found for soilmoisture1: calculate_moisture (key: soilmoisture1, value: 32.0)[0m
2022-06-09T21:54:50.628944574Z | stdout | [94m2022-06-09 21:54:50,627 \| ecowitt2mqtt \| DEBUG \| Calculator found for baromabsin: calculate_pressure (key: baromabs, value: 24.56)[0m
2022-06-09T21:54:50.627056052Z | stdout | [94m2022-06-09 21:54:50,626 \| ecowitt2mqtt \| DEBUG \| Calculator found for baromrelin: calculate_pressure (key: baromrel, value: 24.56)[0m
2022-06-09T21:54:50.626826509Z | stdout | [94m2022-06-09 21:54:50,626 \| ecowitt2mqtt \| DEBUG \| Calculator found for humidityin: calculate_humidity (key: humidityin, value: 35.0)[0m
2022-06-09T21:54:50.626459659Z | stdout | [94m2022-06-09 21:54:50,626 \| ecowitt2mqtt \| DEBUG \| Calculator found for tempinf: calculate_temperature (key: tempin, value: 80.24)[0m
2022-06-09T21:54:50.626190069Z | stdout | [94m2022-06-09 21:54:50,625 \| ecowitt2mqtt \| DEBUG \| Calculator found for runtime: calculate_runtime (key: runtime, value: 1187638.0)[0m

`

**Comment by bachya** [comment] 2022-06-10 04:01
I'm not sure what your describing. The end of that look looks like it still attempts to publish to MQTT.

I recall you are running on a Synology. What Python version? What Docker version?

**Comment by bachya** [comment] 2022-06-10 19:51
Anecdotally, mine has been running fine for over 24 hours using the `amd64` Docker image on a base Debian install.

**Comment by yieldhog** [comment] 2022-06-10 21:29
Thanks -- sorry, yeah it's odd. Only container that's ever crashed on me after some period of time. All prior releases of this package were up for months w/out issue. Latest versions available for Synology, they're typically not bleeding edge.

Docker 20.10.3-1306
Python: 2.7.18-1004

**Comment by bachya** [comment] 2022-06-10 22:27
> Python: 2.7.18-1004

If that means Python 2.x. that's a problem: this library only officially supports Python 3.x.

**Comment by bachya** [comment] 2022-06-10 22:30
The only difference is that I have Docker version 20.10.14, build a224086. Is there any way to run the Docker image on something other than your Synology (so we can try to isolate it as the issue)?

**Comment by yieldhog** [comment] 2022-06-10 22:51
Looks like there’s a beta for Synology to upgrade to 3x, dumb question but safe to assume it’s backward compatible? I don’t want to blow up my other containers. I don’t have another machine w docker ready to go to test unfortunately

https://www.synology.com/en-us/dsm/packages/py3k

**Comment by bachya** [comment] 2022-06-10 23:00
I'm not a Synology expert, unfortunately. I would recommend taking a backup of all of your Docker volumes before any upgrade.

**Comment by alexdelprete** [comment] 2022-06-11 19:44
> Looks like there’s a beta for Synology to upgrade to 3x, dumb question but safe to assume it’s backward compatible? I don’t want to blow up my other containers.

Why do you want to upgrade python? If you use docker, python 3 would be in the container. As you can see from the log, the container is using python 3.10.

If Python was a problem, previous versions wouldn't have worked, and you wrote they did.

It's a "core dump" error, do you have enough hw resources? disk, ram, etc.

Check docker version by running this from shell: `docker version`

**Comment by yieldhog** [comment] 2022-06-12 21:55
You're correct -- it is python3 within the container. Docker 20.10.3-1306. I have plenty of resources, ~7gb of RAM free, ~90% CPU free. It runs for ~24h before crashing, consistently. Odd.

**Comment by alexdelprete** [comment] 2022-06-13 15:41
This is the output of `docker version` from my synology DS1812+, please note that I'm running my main Docker instance on a dedicated VM on my proxmox server, so I can't compare to your setup:

```
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.6
 Git commit:        b35e731
 Built:             Fri Jun 18 08:25:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.6
  Git commit:       e7f7c95
  Built:            Fri Jun 18 08:26:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        b1dc45ec561bd867c4805eee786caab7cc83acae
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        89783e1862a2cc04647ab15b6e88a0af3d66fac3
 docker-init:
  Version:          0.19.0
  GitCommit:        12b6a20
```

**Comment by bachya** [comment] 2022-06-13 20:17
@alexdelprete Since you have a Synology, would you be willing to spin up an instance of `ecowitt2mqtt` (via Docker) and see if you encounter the same crash at some point?

**Comment by alexdelprete** [comment] 2022-06-13 20:32
> would you be willing to spin up an instance of `ecowitt2mqtt` (via Docker) and see if you encounter the same crash at some point?

I already had it in my task-list. :)

Will let you know...but I don't think it's a problem of the container, if previous versions were working, and you didn't make any major changes to the container...

**Comment by alexdelprete** [comment] 2022-06-13 21:00
I started ecowitt2mqtt on my synology, it seems to be working fine. Will wait 24h and report back.

**Comment by yieldhog** [comment] 2022-06-14 00:27
@alexdelprete Here is my docker version output. I run ~15 containers, haven't had one crash yet. I suppose I could have this auto restart but was hoping to try and help troubleshoot since it seems to have started with the new release changes. Mine looks similar but, runs a higher go version for whatever reason.

````
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.17.1
 Git commit:        55f0773
 Built:             Thu Mar 17 08:33:54 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.1
  Git commit:       b487c8f
  Built:            Thu Mar 17 08:32:12 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        3fa00912415f3e9c6f82dd72119179d599efd13b
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        31cc25f16f5eba4d0f53e35374532873744f4b31
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00
```

**Comment by alexdelprete** [comment] 2022-06-14 11:44
Can you please tell us last version it worked without crashes? So @bachya can check exactly what changes have been made and we can try to pin the problem. For me no crashes for now...but it's running since 14 hours. Tonight I'll be able to tell you if I passed the 24h without crashes.

**Comment by alexdelprete** [comment] 2022-06-15 09:54
@bachya Aaron, I can confirm the problem. It stops, it seems randomly, but I don't know. Sometimes I restart it and it stops after some minutes, sometimes it stops after some hours. It's something specific to Synology's Docker, because on my homelab setup (VM with proxmox) I have zero issues.

I don't know how to debug properly to understand what causes the issue. In the debug log I see no errors, it captures data, it exports it to MQTT then all of the sudden it stops.

**Comment by yieldhog** [comment] 2022-06-15 13:46
Ironically, mine has been running a little over 24h now after upgrading to the latest version. Will report back if/when it crashes.

**Comment by alexdelprete** [comment] 2022-06-15 13:57
> Bummer, but at least it's reproducible! @alexdelprete, does the container log in Synology show anything different?

the docker management implementation of synology is pretty dumb. I couldn't see anything meaningful.

now that we know there's a problem, at least for some docker implementations, could you check what you modified since last version that was working for @yieldhog? changes to dockerfile?

**Comment by bachya** [comment] 2022-06-15 14:01
Unfortunately, a lot of was modified – in particular, #144 introduced a whole rearchitecture.

I'm thinking that a `pyspy` session may be useful. I'll follow up shorty with instructions.

**Comment by yieldhog** [comment] 2022-06-15 14:05
I made no changes, deleted my container and reinstalled with the most
recent version

**Comment by alexdelprete** [comment] 2022-06-15 14:06
> I made no changes, deleted my container and reinstalled with the most recent version

sorry, the question was for Aaron. :)

**Comment by bachya** [comment] 2022-06-15 14:44
My `py-spy` run isn't yielding anything obvious.

@yieldhog, I'm coming back to versions. On my Proxmox LXC, I'm running:

* Docker 20.10.14
* containerd 1.5.11-1

...whereas you have:

* Docker 20.10.3
* containerd: 1.4.3

I know you aren't having issues with other containers. Still, given that we can't see anything obvious or reproducible outside of the Synology ecosystem, that's the only difference I can see...

That said, let's keep your current test (with the latest `dev`) running for a bit longer. Your log seems to indicate the crash happened in the `server` module (the component that serves the REST API) and was related to threading; I recently reworked all of that into a proper async pattern, so perhaps that fixes things.

**Comment by bachya** [comment] 2022-06-16 14:03
@yieldhog Curious to hear an update: has your latest test continued on, or crashed again?

**Comment by yieldhog** [comment] 2022-06-16 14:33
Hi -- it crashed last evening, same error. Managed to run ~2 days.

**Comment by bachya** [comment] 2022-06-16 15:05
Darn, that's too bad. Thanks for following up.

Unfortunately, since I can't reproduce and don't own a Synology, I'm out of ideas at the moment. I'll post back here if I think of anything new to try. In the meantime, maybe you can do some research and see if there's a way – perhaps through the Synology CLI – to get more information on container crashes.

**Comment by yieldhog** [comment] 2022-06-25 23:03
Oddly it last managed to run 5-6 days before crashing. Updated to your latest version and seeing what happens.

**Comment by bachya** [comment] 2022-06-25 23:09
Aghh, why can issues never be consistent?  😂

**Comment by bachya** [comment] 2022-07-25 03:10
@yieldhog Following up here. Can you remind me whether you use Home Assistant MQTT Discovery?

**Comment by yieldhog** [comment] 2022-07-25 03:28
@bachya hi -- I do use MQTT Discovery. I should've come back earlier, but, appears the docker container has been up 6 days+ at the moment.

**Comment by bachya** [comment] 2022-07-25 04:01
I've run across a couple of additional other reports of people experiencing crashes, resource hogging, etc. while using MQTT Discovery. For what it's worth, it looks like it would affect people who are losing connection to their MQTT broker every now and again. I forget: was that possibly you, as well?

**Comment by bachya** [comment] 2022-07-25 05:34
@yieldhog When you get a chance, try upgrading to https://github.com/bachya/ecowitt2mqtt/releases/tag/2022.07.4 and see if that helps (if you use Docker, wait for the image to [build](https://github.com/bachya/ecowitt2mqtt/actions/runs/2730113566)).

**Comment by yieldhog** [comment] 2022-07-25 14:37
@bachya thanks, I installed -- will see how it goes and looking forward to checking out your official add-on when its ready.

**Comment by bachya** [comment] 2022-07-27 03:31
Per https://github.com/bachya/ecowitt2mqtt/issues/182#issuecomment-1196222925, it looks like #228 has fixed this, as well. Closing.

**Closed by bachya** 2022-07-27 03:31 UTC
Labels: bug
