### ISSUE TITLE
MQTT stops publishing after some time on 2022.06.xx

### ISSUE THREAD

**Issue by aklaiber82** [bachya/ecowitt2mqtt#182] opened 2022-06-15 14:51 UTC
Running 2022.06.xx versions and dev I appear to get a timeout and crash error publishing to mqtt.  Had previously run versions 2022.05.xx and 2022.04.xx with no issues.  Have just downgraded back to 2022.05 to confirm it is nothing else on my end that could be causing this and will update if I see anything error on the old version.  Running this as a docker container on ubuntu publishing to eclipse-mosquitto.

Here is the last of the log file when it stops/freezes:

```
2022-06-15 13:58:56,990 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:03,063 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:25,397 | asyncio | ERROR | Task exception was never retrieved
future: <Task finished name='Task-239090' coro=<HomeAssistantDiscoveryPublisher.async_publish() done, defined at /venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py:357> exception=PublishError('Error while publishing to Home Assisstant MQTT Discovery: Operation timed out')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 390, in _wait_for
    return await asyncio.wait_for(fut, timeout=timeout, **kwargs)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 378, in async_publish
    await asyncio.gather(*futures)
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 99, in decorated
    return await method(self, *args, **kwargs)
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 285, in publish
    await self._wait_for(confirmation.wait(), timeout=timeout)
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 392, in _wait_for
    raise MqttError("Operation timed out")
asyncio_mqtt.error.MqttError: Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 382, in async_publish
    raise PublishError(
ecowitt2mqtt.helpers.publisher.PublishError: Error while publishing to Home Assisstant MQTT Discovery: Operation timed out
2022-06-15 13:59:25,727 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:25,737 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:27,050 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:33,075 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:40,934 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:45,089 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 13:59:51,297 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 14:00:07,022 | asyncio | ERROR | Task exception was never retrieved
future: <Task finished name='Task-241525' coro=<HomeAssistantDiscoveryPublisher.async_publish() done, defined at /venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py:357> exception=PublishError('Error while publishing to Home Assisstant MQTT Discovery: [code:4] The client is not currently connected.')>
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 378, in async_publish
    await asyncio.gather(*futures)
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 99, in decorated
    return await method(self, *args, **kwargs)
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 277, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
asyncio_mqtt.error.MqttCodeError: [code:4] The client is not currently connected.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 382, in async_publish
    raise PublishError(
ecowitt2mqtt.helpers.publisher.PublishError: Error while publishing to Home Assisstant MQTT Discovery: [code:4] The client is not currently connected.
```

**Comment by bachya** [comment] 2022-06-15 15:01
Your logs seem to indicate a timeout when publishing to your MQTT broker. Can you run the Docker container with the `ECOWITT2MQTT_VERBOSE` environment variable set to `true` and share the logs again?

**Comment by aklaiber82** [comment] 2022-06-15 15:23
Yes, using the image linked.  Re-pulled the dev version just now to confirm and am running verbose logs.  Typically runs about an hour or so until freezes up.  Will post the logs once it happens.

**Comment by aklaiber82** [comment] 2022-06-15 20:15
Not sure what to make of this but I can describe the experience.  Some sensors seem "frozen" and are not updating over mqtt while they are updating fine when publishing to ecowitt.net.  I have attached a log.  Sometimes all sensors seem to freeze up.  For example, my temperature is updating just fine but my "feels like" hasn't updated in several hours.  Similar weirdness for other sensors.

So...not sure if my end has something weird going on or there is something in the log that can help.

[freezeing_logs_v1.txt](https://github.com/bachya/ecowitt2mqtt/files/8912782/freezeing_logs_v1.txt)
.

**Comment by bachya** [comment] 2022-06-15 20:40
I don't see any trace of the previously-mentioned exception in those logs – everything looks as it should. I notice you left diagnostics enabled; that will publish one payload, then exit, then startup again, etc. That could account for the lapse in data you're seeing.

**Comment by aklaiber82** [comment] 2022-06-15 20:44
Ok.  I will turn off diagnostics and run longer.  Feel free to close it for now.

**Comment by aklaiber82** [comment] 2022-06-15 21:51
Well...I spoke too early.  When removing the verbose log it doesn't constantly reset and after about 20 minutes I got the error again.  Not sure how exactly to log this since the verbose setting I was using seemed to restart it too soon.  Happy to help if I can figure this out.

2022-06-15 20:55:48,489 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 20:55:53,627 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 20:55:59,706 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 20:56:05,658 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-15 20:56:21,491 | asyncio | ERROR | Task exception was never retrieved
future: <Task finished name='Task-6452' coro=<HomeAssistantDiscoveryPublisher.async_publish() done, defined at /venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py:370> exception=PublishError('Error while publishing to Home Assisstant MQTT Discovery: [code:4] The client is not currently connected.')>
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 391, in async_publish
    await asyncio.gather(*futures)
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 99, in decorated
    return await method(self, *args, **kwargs)
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 277, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
asyncio_mqtt.error.MqttCodeError: [code:4] The client is not currently connected.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 395, in async_publish
    raise PublishError(
ecowitt2mqtt.helpers.publisher.PublishError: Error while publishing to Home Assisstant MQTT Discovery: [code:4] The client is not currently connected.

**Comment by bachya** [comment] 2022-06-15 22:09
Can you show me how you're setting verbose? That's a different setting from diagnostics, and your log showed you running diagnostics.

**Comment by aklaiber82** [comment] 2022-06-15 22:15
I am re-making the docker:

sudo docker run -it --restart=always -e ECOWITT2MQTT_VERBOSE=true -e MQTT_BROKER=192.168.1.81 -e MQTT_USERNAME= -e MQTT_PASSWORD= -p 8080:8080  -e HASS_DISCOVERY=true -e HASS_DISCOVERY_PREFIX=homeassistant bachya/ecowitt2mqtt:dev

**Comment by bachya** [comment] 2022-06-15 22:21
Interesting – you've helped me see a separate bug: unintentional diagnostics! Will fix that separately.

RE: the main issue, it still seems like, after a while, your `ecowitt2mqtt` may lose connection to the MQTT broker and never recover. I'm going to try to address that ("don't die if you lose connection; just try again the next time around") in a new `dev` image and will le you know when it's available to test./

**Comment by aklaiber82** [comment] 2022-06-15 22:22
Sounds good.  Thanks.  Sorry for helping to debug all of a sudden!

**Comment by bachya** [comment] 2022-06-15 23:57
@aklaiber82 I've implemented the "don't die if you lose connection" logic in #185, which is being built into a `dev` Docker image [now](https://github.com/bachya/ecowitt2mqtt/actions/runs/2505828012). Once the build completes, give it a try – even if the connection to the MQTT broker fails, it should try again the next time around. Post back here if you need further assistance.

**Comment by aklaiber82** [comment] 2022-06-16 00:24
Thanks so much!

**Comment by bachya** [comment] 2022-06-16 16:43
I don't see any errors in those logs. Can you tell me what you're noticing in terms of freezing? Does the log just stop when you know the device is still transmitting data?

**Comment by aklaiber82** [comment] 2022-06-16 16:53
All the data simply stops updating.  I don't see anything obvious in the logs but all my sensor information flatlines.  Had never seen this prior to the 2022.06 versions.

**Comment by aklaiber82** [comment] 2022-06-16 18:26
Zero freezing on 2022.5.0.  Ran all last night before swapping to the dev version today.  Running 2022.5.0 again now with no issues.

**Comment by bachya** [comment] 2022-06-16 18:44
Got it; thanks for confirming. Unfortunately, since I can't reproduce here (I've been running 2022.06.x for several days with no freeze) and the logs don't show anything, I don't have any ideas at the moment. Will leave this open to see if anybody else can corroborate.

**Comment by aklaiber82** [comment] 2022-06-16 22:05
I got it to error again but didn't catch a verbose log.  It appears to simply lose the mqtt client connection and never recover.  Just dies at the final line.  Going to restart with a verbose log and see if I can catch when it dies.

>
2022-06-16 22:01:12,995 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-16 22:01:19,003 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-16 22:01:20,721 | ecowitt2mqtt | INFO | Published to Home Assistant MQTT Discovery
2022-06-16 22:01:33,129 | ecowitt2mqtt | ERROR | Unable to publish payload: Error while publishing to Home Assisstant MQTT Discovery: [code:4] The client is not currently connected.

**Comment by aklaiber82** [comment] 2022-06-16 23:03
I can't exactly capture what happens in the logs, but I do know what is missing.  When it loses connection, it continues to accept data from the ecowitt gateway, executes the calling on field and eventually the calculator step with the ecowitt data and then runs the following two lines:

2022-06-16 22:51:13,761 | ecowitt2mqtt | DEBUG | Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) client_id=b''
2022-06-16 22:51:13,766 | ecowitt2mqtt | DEBUG | Received CONNACK (0, 0)

At this point, I would expect that it would execute a whole series of "Sending Publish ...." with the sensor data but that doesn't occur.  Instead, it simply repeats all the prior steps with the new ecowitt gateway data it received and fails to execute the "sending publish" commands to post the sensor data to mqtt.

**Comment by bachya** [comment] 2022-06-17 03:42
That's exactly what happens on my instance. Do debug logs show any sort of error related to losing connection to the MQTT broker?

**Comment by aklaiber82** [comment] 2022-06-17 13:52
I am struggling to get the full log out of the docker container and will keep trying to figure out where it is.  My guess from watching real-time logs is that once it loses connection it might reconnect but never sends the publish command again.  But...this is just a guess.  Will google for how to extract/set a log file name and path and see if I can get a complete one.

**Comment by bachya** [comment] 2022-06-17 20:45
Thanks for all the research, @aklaiber82!

The only issues I see in there are errors about you being disconnected from your MQTT broker – for example:

```
2022-06-17 13:46:06,536 | ecowitt2mqtt | ERROR | Unable to publish payload: Error while publishing to Home Assisstant MQTT Discovery: [code:4] The client is not currently connected.
```

The issue you referenced:

```
2022-06-17 13:48:12,885 | asyncio | ERROR | Exception in callback <function Client._on_socket_open.<locals>.cb at 0x7fe8bb801750>
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/asyncio_mqtt/client.py", line 516, in cb
    client.loop_read()
  File "/venv/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/venv/lib/python3.10/site-packages/paho/mqtt/client.py", line 2389, in _packet_read
    byte = self._sock_recv(1)
  File "/venv/lib/python3.10/site-packages/paho/mqtt/client.py", line 640, in _sock_recv
    return self._sock.recv(bufsize)
AttributeError: 'NoneType' object has no attribute 'recv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
```

...isn't even in my code: it's in the underlying MQTT library (which I've used since the beginning, interestingly). So, unfortunately, I don't think we have a smoking gun just yet.

**Comment by bachya** [comment] 2022-07-25 05:33
@aklaiber82 When you get a chance, try upgrading to https://github.com/bachya/ecowitt2mqtt/releases/tag/2022.07.4 and see if that helps.

**Comment by aklaiber82** [comment] 2022-07-25 19:09
Trying the new version 2022.07.4 now.  Will update status soon.

**Comment by aklaiber82** [comment] 2022-07-26 23:25
Still going perfectly after 30 hours.  I am guessing this issue is resolved now.  Will update if I experience it again but don't expect it to show up at this point.  Thanks for keeping this on the radar screen!

**Comment by bachya** [comment] 2022-07-26 23:36
Great news, @aklaiber82! Will close this out, but please comment back if it happens again. Thanks for your patience!

**Closed by bachya** 2022-07-26 23:36 UTC
Labels: bug

**Comment by yieldhog** [comment] 2022-07-27 03:27
Mine has been running as well with no issues, thank you

**Comment by bachya** [comment] 2022-07-27 03:30
Awesome, @yieldhog! Same deal: I'll close your issue and if you experience challenges later on, feel free to re-open.
