### ISSUE TITLE
BUG: ecowitt2mqtt sometimes stops reporting to HA

### ISSUE THREAD

**Issue by JvdMaat** [bachya/ecowitt2mqtt#789] opened 2023-11-21 13:31 UTC
**Describe the bug**
Every so often (I have observed it 3 times in the past 2 weeks now), HA stops seeing values from Ecowitt. Restarting the ecowitt2mqtt container fixes this. I just did this for the 3rd time, and now feel it's a pattern. I do not have logs. Please let me know what to enable for debugging, or where to get logs next time this happens (should be in the next week).
I did check the container logs, and it's sending the standard message regularly (I'm guessing 8 times a minute since I have 2 devices) 
```
2023-11-21 08:00:16,567 | INFO | Published to Home Assistant MQTT Discovery
```

**To Reproduce**
Just running the container and waiting a week.

**Additional context**
This is a new issue that has started November 5th. So it may be something introduced with the 2023.11 version.
Next time I'll grab an MQTT Explorer output to see what's in there. Is there anything in the container to enable for more in depth debugging? I just enabled ECOWITT2MQTT_DIAGNOSTICS, and did notice this:

```
2023-11-21 08:25:27,771 | INFO | *** DIAGNOSTICS COLLECTED
2023-11-21 08:25:27,771 | DEBUG | Stopping runtime
2023-11-21 08:25:27,771 | DEBUG | Runtime shutdown complete
2023-11-21 08:25:27,772 | DEBUG | Sending DISCONNECT
2023-11-21 08:25:27,772 | DEBUG | Stopping MQTT process loop
ERROR:    Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/venv/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
```
(This seems to happen after every publish data event)

**Comment by JvdMaat** [comment] 2023-11-21 13:41
With the ECOWITT2MQTT_DIAGNOSTICS enabled, my Uptime Kuma is reporting ecowitt2mqtt down regularly.
![image](https://github.com/bachya/ecowitt2mqtt/assets/90044149/b21e5720-3ec1-490b-80cb-141f2cd41a67)
I'm updating that to allow for more retries for now (since we do want the diagnostics for when this breaks again). But something is now preventing network access (Uptime Kuma is just checking if port 8080 can receive TCP. Nothing more)

**Comment by bachya** [comment] 2023-11-21 14:45
This is a duplicate of #760. Try the suggestion in [this comment](https://github.com/bachya/ecowitt2mqtt/issues/760#issuecomment-1809429460) and if the problem persists, please contribute any additional information over there. Thanks for your help!

**Closed** 2023-11-21 14:45 UTC
Labels: bug, python

**Comment by JvdMaat** [comment] 2023-11-21 14:52
No problem. It didn't look the same as that (at first glance) looked like it did not work at all (versus stopping after a while).
But on reading the thread it seems like this is indeed related. I just checked my outage times, and it was pretty much when I upgraded HA (so HA went down for reboot).
